# Generated by Django 3.0.2 on 2021-04-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_merge_20210223_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=264)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Report',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1)),
            ],
            options={
                'verbose_name_plural': 'ReportGroup',
                'db_table': 'report_group',
            },
        ),
        migrations.CreateModel(
            name='ReportKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1)),
                ('value_type', models.IntegerField(choices=[(1, 'Double'), (2, 'String')], default=1)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Report')),
                ('report_group_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_group_one', to='report.ReportGroup')),
                ('report_group_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_group_two', to='report.ReportGroup')),
            ],
            options={
                'verbose_name_plural': 'ReportKey',
                'db_table': 'report_key',
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('double', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('string', models.CharField(blank=True, max_length=264, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Department')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Region')),
                ('report_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.ReportKey')),
            ],
            options={
                'verbose_name_plural': 'ReportValue',
                'db_table': 'report_value',
            },
        ),
    ]
