# Generated by Django 3.0.2 on 2021-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportvalue',
            name='date',
            field=models.DateField(default='2021-04-07'),
            preserve_default=False,
        ),
    ]
