# Generated by Django 3.0.2 on 2021-04-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportvalue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportkey',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportvalue',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
        ),
    ]
