# Generated by Django 3.0.2 on 2021-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210413_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportvalue',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1),
        ),
    ]
