# Generated by Django 3.0.2 on 2021-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportvalue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, 'Moliya'), (2, 'Urmon-barpo'), (3, 'Chorvachilik'), (4, "Qishloq-xo'jaligi"), (5, "O'rmon maxsulotlari"), (6, 'Tanlanmagan')], default=6),
        ),
    ]
