# Generated by Django 3.0.2 on 2021-11-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210624_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Summary'), (2, 'Listed')], default=1),
        ),
    ]
