# Generated by Django 3.0.2 on 2021-11-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportvalue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
