# Generated by Django 3.0.2 on 2021-01-14 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'TreeCategory',
                'db_table': 'tree_category',
            },
        ),
        migrations.CreateModel(
            name='TreePlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
            ],
            options={
                'verbose_name_plural': 'TreePlant',
                'db_table': 'tree_plant',
            },
        ),
        migrations.CreateModel(
            name='TreeHeightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('height_0_0_2_count', models.FloatField(blank=True, null=True, verbose_name='0,2 м гача')),
                ('height_0_2_5_count', models.FloatField(blank=True, null=True, verbose_name='0,2 дан 0,5 м гача')),
                ('height_0_5_1_count', models.FloatField(blank=True, null=True, verbose_name='0,5 -1 м. гача')),
                ('height_1_1_5_count', models.FloatField(blank=True, null=True, verbose_name='1-1,5 м гача')),
                ('height_1_5_2_count', models.FloatField(blank=True, null=True, verbose_name='1,5-2 м гача')),
                ('height_2_count', models.FloatField(blank=True, null=True, verbose_name='2 м дан')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
                ('tree_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
            ],
            options={
                'verbose_name_plural': 'TreeHeightReport',
                'db_table': 'tree_height',
            },
        ),
    ]
