# Generated by Django 3.0.2 on 2021-01-18 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0003_growingplant_growingplantplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowingPlant',
            new_name='Sapling',
        ),
        migrations.RenameModel(
            old_name='GrowingPlantPlan',
            new_name='SaplingPlan',
        ),
        migrations.AlterModelOptions(
            name='sapling',
            options={'verbose_name_plural': 'Sapling'},
        ),
        migrations.AlterModelOptions(
            name='saplingplan',
            options={'verbose_name_plural': 'SaplingPlan'},
        ),
        migrations.AlterModelTable(
            name='sapling',
            table='sapling',
        ),
        migrations.AlterModelTable(
            name='saplingplan',
            table='sapling_plan',
        ),
        migrations.CreateModel(
            name='SproutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprout_plan_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_plan_department', to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_plan_plant', to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_plan_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SproutPlan',
                'db_table': 'sprout_plan',
            },
        ),
        migrations.CreateModel(
            name='Sprout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprout_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_department', to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_plant', to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprout_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'Sprout',
                'db_table': 'sprout',
            },
        ),
        migrations.CreateModel(
            name='SeedPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed_plan_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_plan_department', to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_plan_plant', to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_plan_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SeedPlan',
                'db_table': 'seed_plan',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_department', to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_plant', to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'Seed',
                'db_table': 'seed',
            },
        ),
    ]
