# Generated by Django 3.0.2 on 2021-01-18 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('trees', '0004_auto_20210118_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='SproutOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('for_the_forest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('selling', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unsuccessful', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('place_changed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SproutOutput',
                'db_table': 'sprout_output',
            },
        ),
        migrations.CreateModel(
            name='SproutInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('buying', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('new_sprout', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SproutInput',
                'db_table': 'spout_input',
            },
        ),
        migrations.CreateModel(
            name='SeedOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('for_the_forest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('selling', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unsuccessful', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('place_changed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SeedOutput',
                'db_table': 'seed_output',
            },
        ),
        migrations.CreateModel(
            name='SeedInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('buying', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('new_sprout', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SeedInput',
                'db_table': 'seed_input',
            },
        ),
        migrations.CreateModel(
            name='SaplingOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('for_the_forest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('selling', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unsuccessful', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('place_changed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SaplingOutput',
                'db_table': 'sapling_output',
            },
        ),
        migrations.CreateModel(
            name='SaplingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('buying', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('new_sprout', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreePlant')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'SaplingInput',
                'db_table': 'sapling_input',
            },
        ),
    ]
