# Generated by Django 3.0.2 on 2021-01-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_auto_20210121_1333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sproutinput',
            table='sprout_input',
        ),
    ]
