# Generated by Django 3.0.2 on 2021-01-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_treegroundplanting_treegroundplantingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'TreeTypes',
                'db_table': 'tree_types',
            },
        ),
        migrations.AddField(
            model_name='treeplant',
            name='types',
            field=models.ManyToManyField(related_name='tree_types', to='trees.TreeCategory', verbose_name='Tree types'),
        ),
    ]
