# Generated by Django 3.0.2 on 2021-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_auto_20210129_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplant',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='tree_types', to='trees.TreeTypes', verbose_name='Tree types'),
        ),
    ]
