# Generated by Django 3.0.2 on 2021-02-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_auto_20210129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.TreeCategory'),
        ),
    ]
