# Generated by Django 3.0.2 on 2021-02-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0014_treetypes_show_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplant',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='tree_types', to='trees.TreeTypes', verbose_name='Tree types'),
        ),
    ]
