# Generated by Django 3.0.2 on 2021-03-16 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20210223_1523'),
        ('trees', '0016_auto_20210223_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeContractCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')])),
            ],
            options={
                'verbose_name_plural': 'TreeContractCategory',
                'db_table': 'tree_contract_category',
            },
        ),
        migrations.CreateModel(
            name='TreeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('output_tree', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreeContractCategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'TreeContract',
                'db_table': 'tree_contract',
            },
        ),
    ]
