# Generated by Django 3.0.2 on 2021-03-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0018_auto_20210316_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saplingplan',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sapling_plan', to='trees.TreePlant'),
        ),
    ]
