# Generated by Django 3.0.2 on 2021-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0019_auto_20210318_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeplant',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='SORT NUMBER'),
        ),
    ]
