# Generated by Django 3.0.2 on 2021-07-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0021_auto_20210407_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='treetypes',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='SORT NUMBER'),
        ),
    ]
