# Generated by Django 3.0.2 on 2021-02-08 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_department_parent_id'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionServicePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('production', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paid_service', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'ProductionServicePlan',
                'db_table': 'production_service_plan',
            },
        ),
        migrations.CreateModel(
            name='ProductionServiceActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('production', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paid_service', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'ProductionServiceActual',
                'db_table': 'production_service_actual',
            },
        ),
    ]
