# Generated by Django 3.0.2 on 2021-02-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_productionserviceactual_productionserviceplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='amount_type',
            field=models.IntegerField(choices=[(1, "Ho'jalik"), (2, 'HUSUSIY SECTOR')], default=1),
        ),
        migrations.AddField(
            model_name='financeplan',
            name='amount_type',
            field=models.IntegerField(choices=[(1, "Ho'jalik"), (2, 'HUSUSIY SECTOR')], default=1),
        ),
    ]
