# Generated by Django 3.0.2 on 2021-02-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210211_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
