# Generated by Django 3.0.2 on 2021-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='financeplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='financetype',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='productionserviceactual',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='productionserviceplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
    ]
