# Generated by Django 3.0.2 on 2021-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20210223_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='state',
            field=models.IntegerField(choices=[(1, 'NEW'), (2, 'CONFIRM'), (3, 'DELETE')], default=1),
        ),
    ]
