# Generated by Django 3.0.2 on 2021-02-01 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210128_1536'),
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Animal',
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='AnimalTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'AnimalType',
                'db_table': 'animal_types',
            },
        ),
        migrations.CreateModel(
            name='AnimalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('amount_type', models.IntegerField(choices=[(1, 'PCS'), (2, 'KG'), (3, 'HEAD'), (4, 'TON'), (5, 'FAMILY')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_animal_plan', to='agriculture.Animal')),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_plan_type', to='agriculture.AnimalTypes')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_plan_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_plan_department', to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_plan_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'AnimalPlan',
                'db_table': 'animal_plan',
            },
        ),
        migrations.CreateModel(
            name='AnimalActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('amount_type', models.IntegerField(choices=[(1, 'PCS'), (2, 'KG'), (3, 'HEAD'), (4, 'TON'), (5, 'FAMILY')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_animal_actual', to='agriculture.Animal')),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_actual_type', to='agriculture.AnimalTypes')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_actual_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_actual_department', to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_actual_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'AnimalActual',
                'db_table': 'animal_actual',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='animals_type', to='agriculture.AnimalTypes'),
        ),
    ]
