# Generated by Django 3.0.2 on 2021-02-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_auto_20210201_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='chorvachilik',
        ),
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='chorvachilik_type',
        ),
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='department',
        ),
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='region',
        ),
        migrations.RemoveField(
            model_name='chorvachilikplan',
            name='chorvachilik',
        ),
        migrations.RemoveField(
            model_name='chorvachilikplan',
            name='chorvachilik_type',
        ),
        migrations.RemoveField(
            model_name='chorvachilikplan',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chorvachilikplan',
            name='department',
        ),
        migrations.RemoveField(
            model_name='chorvachilikplan',
            name='region',
        ),
        migrations.DeleteModel(
            name='Chorvachilik',
        ),
        migrations.DeleteModel(
            name='ChorvachilikActual',
        ),
        migrations.DeleteModel(
            name='ChorvachilikPlan',
        ),
        migrations.DeleteModel(
            name='ChorvachilikTypes',
        ),
    ]
