# Generated by Django 3.0.2 on 2021-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_auto_20210203_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureactual',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
