# Generated by Django 3.0.2 on 2021-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_agricultureactual_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureactual',
            name='yield_area',
            field=models.FloatField(blank=True, null=True, verbose_name='yield_area'),
        ),
    ]
