# Generated by Django 3.0.2 on 2021-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0006_agricultureactual_yield_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureactual',
            name='show_yield_area',
            field=models.BooleanField(default=False),
        ),
    ]
