# Generated by Django 3.0.2 on 2021-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0007_agricultureactual_show_yield_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureactual',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='agricultureplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
    ]
