# Generated by Django 3.0.2 on 2021-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='is_judicial',
            field=models.BooleanField(default=False),
        ),
    ]
