# Generated by Django 3.0.2 on 2021-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210202_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cripple',
            field=models.IntegerField(choices=[(1, 'Yoq'), (2, 'Xa')], default=1, verbose_name='Ногиронлиги'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixin')], default=1),
        ),
    ]
