# Generated by Django 3.0.2 on 2021-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210202_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
