# Generated by Django 3.0.2 on 2021-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210206_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='birth_place',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Tugilgan joyi'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='favorite_party',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Qaysi partiya a'zosi"),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='judicial',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Суд жавобгарлигига тортилган бўлсангиз, қачон ва нима учун'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='languages',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Qaysi chet tillarini bilasiz qay darajada'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='military_service',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ҳарбий хизматга муносабати ва ҳарбий унвони'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='people_deputy',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Xalq deputatat azosimi agar bolsa toliq malumot'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='residence_address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Yashash joyi MFY'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='specialization',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Mutahasislik'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='state_award',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Давлат мукофотлари билан тақдирланганми (қанақа)'),
        ),
    ]
