# Generated by Django 3.0.2 on 2021-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210206_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_child', to='accounts.Department'),
        ),
    ]
