# Generated by Django 3.0.2 on 2021-02-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210218_1322'),
        ('accounts', '0014_auto_20210218_0417'),
    ]

    operations = [
    ]
