# Generated by Django 3.0.2 on 2021-02-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userinformation_diploma_number'),
        ('accounts', '0019_auto_20210223_0830'),
    ]

    operations = [
    ]
