# Generated by Django 3.0.2 on 2021-02-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20210223_0945'),
        ('accounts', '0020_merge_20210223_0858'),
    ]

    operations = [
    ]
