# Generated by Django 3.0.2 on 2021-02-03 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210202_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chorvachilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Chorvachilik',
                'db_table': 'chorvachilik',
            },
        ),
        migrations.CreateModel(
            name='ChorvachilikTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'ChorvachilikType',
                'db_table': 'chorvachilik_types',
            },
        ),
        migrations.CreateModel(
            name='ChorvachilikPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('amount_type', models.IntegerField(choices=[(1, 'PCS'), (2, 'KG'), (3, 'HEAD'), (4, 'TON'), (5, 'FAMILY')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('chorvachilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_plan_chorvachilik', to='chorvachilik.Chorvachilik')),
                ('chorvachilik_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_plan_type', to='chorvachilik.ChorvachilikTypes')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_plan_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_plan_department', to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_plan_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'ChorvachilikPlan',
                'db_table': 'chorvachilik_plan',
            },
        ),
        migrations.CreateModel(
            name='ChorvachilikActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('amount_type', models.IntegerField(choices=[(1, 'PCS'), (2, 'KG'), (3, 'HEAD'), (4, 'TON'), (5, 'FAMILY')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
                ('chorvachilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_actual_chorvachilik', to='chorvachilik.Chorvachilik')),
                ('chorvachilik_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_actual_type', to='chorvachilik.ChorvachilikTypes')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_actual_creator', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_actual_department', to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chorvachilik_actual_region', to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'ChorvachilikActual',
                'db_table': 'chorvachilik_actual',
            },
        ),
        migrations.AddField(
            model_name='chorvachilik',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='chorvachilik_type', to='chorvachilik.ChorvachilikTypes'),
        ),
    ]
