# Generated by Django 3.0.2 on 2021-02-04 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210202_1312'),
        ('chorvachilik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Animal')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Animal',
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='ChorvaInputOutputCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Kirim yoki chiqim category')),
                ('type', models.IntegerField(choices=[(1, 'INPUT'), (2, 'OUTPUT')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'ChorvaInputOutputCategory',
                'db_table': 'chorva_input_output_category',
            },
        ),
        migrations.CreateModel(
            name='ChorvaInputOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Boshi')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Vazni')),
                ('type', models.IntegerField(choices=[(1, 'INPUT'), (2, 'OUTPUT')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'NEW'), (2, 'CONFIRM'), (2, 'DELETE')], default=1)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorvachilik.Animal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chorvachilik.ChorvaInputOutputCategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Region')),
            ],
            options={
                'verbose_name_plural': 'ChorvaInputOutput',
                'db_table': 'chorva_input_output',
            },
        ),
    ]
