# Generated by Django 3.0.2 on 2021-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0002_animal_chorvainputoutput_chorvainputoutputcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorvainputoutput',
            name='status',
            field=models.IntegerField(choices=[(1, 'NEW'), (2, 'CONFIRM'), (3, 'DELETE')], default=1),
        ),
    ]
