# Generated by Django 3.0.2 on 2021-02-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0003_auto_20210204_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Animal')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Delete')], default=1)),
            ],
            options={
                'verbose_name_plural': 'AnimalCategory',
                'db_table': 'animal_category',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_category', to='chorvachilik.AnimalCategory'),
        ),
    ]
