# Generated by Django 3.0.2 on 2021-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0004_auto_20210205_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorvachilikactual',
            name='yield_area',
            field=models.FloatField(blank=True, null=True, verbose_name='yield_area'),
        ),
    ]
