# Generated by Django 3.0.2 on 2021-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0005_chorvachilikactual_yield_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorvachilik',
            name='show_yield_area',
            field=models.BooleanField(default=False),
        ),
    ]
