# Generated by Django 3.0.2 on 2021-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0006_chorvachilik_show_yield_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorvachilikactual',
            name='yield_area',
        ),
        migrations.AddField(
            model_name='chorvachilikactual',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
