# Generated by Django 3.0.2 on 2021-02-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0008_auto_20210217_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorvachilik',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='chorvachilik_type', to='chorvachilik.ChorvachilikTypes'),
        ),
    ]
