# Generated by Django 3.0.2 on 2021-02-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0009_auto_20210218_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorvachilik',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_chorva', to='chorvachilik.Chorvachilik'),
        ),
    ]
