# Generated by Django 3.0.2 on 2021-02-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0009_auto_20210218_1322'),
        ('chorvachilik', '0010_auto_20210218_0504'),
    ]

    operations = [
    ]
