# Generated by Django 3.0.2 on 2021-02-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0011_merge_20210219_1330'),
        ('chorvachilik', '0010_chorvachilik_parent'),
    ]

    operations = [
    ]
