# Generated by Django 3.0.2 on 2021-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorvachilik', '0013_chorvachilik_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='chorvachilik',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='chorvachilikactual',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='chorvachilikplan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='chorvachiliktypes',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
        migrations.AlterField(
            model_name='chorvainputoutputcategory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'In Active')], default=1),
        ),
    ]
