version: '3'

services:
  statdb:
    container_name: stat-db
    restart: always  
    image: postgres:12.2
    env_file:
      - ./.env.prod.db
    networks:
      - stat-network
    volumes:
        - statdata:/var/lib/postgresql/data/
    
  statweb:
    container_name: stat-web
    restart: always  
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn staturmon.wsgi:application --bind 0.0.0.0:3939
    volumes:
      - static_volume_stat:/home/app/web/static
      - media_volume_stat:/home/app/web/media
    networks:
      - stat-network
    ports:
      - "3939:3939"
    env_file: 
      - ./.env.prod
  statnginx:
    container_name: stat-nginx
    restart: always
    build: ./nginx
    volumes:
      - static_volume_stat:/home/app/web/static
      - media_volume_stat:/home/app/web/media
    ports:
      - "4040:4040"
    networks:
      - stat-network
    depends_on:
      - statweb
      
volumes:
  statdata:
  static_volume_stat:
  media_volume_stat:

networks:
  stat-network:
    driver: bridge
